# vim:set ft=yaml ts=4 sw=4 sts=4 autoindent:

# Configuration file for Travis Continuous Integration (CI).
#
# Author:   Pontus Stenetorp    <pontus stenetorp se>
# Version:  2014-05-27

# Lies! But, apparently this is standard for Julia.
language: c
compiler:
    - clang

notifications:
    email: false

env:
    - JLVERSION="juliareleases"
    - JLVERSION="julianightlies"

matrix:
    allow_failures:
        - env: JLVERSION="julianightlies"
    fast_finish: true

before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository "ppa:staticfloat/${JLVERSION}" -y
    - sudo apt-get update -q -q -y
    - sudo apt-get install libpcre3-dev julia -y
script: |
    if [ "${JLVERSION}" = "julianightlies" ]
    then
        make coverage
    else
        make sanity
    fi
after_success: |
    if [ "${JLVERSION}" = "julianightlies" ]
    then
        julia -e 'Pkg.add("Coverage")'
        julia -e 'using Coverage; Coveralls.submit(Coveralls.process_folder())'
    fi
